Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Debug
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"

# Important if using Git update method
BaseUrl: "http://localhost:5000"

AllowedHosts: "*"

Servers:
  Instances:
    Production:
      Name: "Space Station 14 Server"
      ApiToken: "foobar"
      ApiPort: 1212
      UpdateType: "Git"
      Updates:
        BaseUrl: "https://github.com/space-wizards/space-station-14.git"
